using System.Text;

namespace TextureGrade.Localization
{
    /// <summary>
    /// 内置的操作说明正文。
    /// 用途：插件同级目录下没有 TextureGrade_Operation.txt 时，按当前语言生成一份默认文件，
    /// 用户之后直接改那个 txt 即可（改完点窗口里的「重新载入」）。
    /// </summary>
    public static class DefaultManual
    {
        public static string Get(Lang l)
        {
            switch (l)
            {
                case Lang.ZhCn: return ZhCn() + RecolorTexts.Manual(l);
                case Lang.ZhTw: return ZhTw() + RecolorTexts.Manual(l);
                case Lang.Ja: return Ja() + RecolorTexts.Manual(l);
                default: return En() + RecolorTexts.Manual(l);
            }
        }

        private static string ZhCn() => new StringBuilder()
            .AppendLine("Texture Grade — 操作说明")
            .AppendLine("（本文件由插件自动生成，可随意编辑；改完在说明窗口点「重新载入」即可看到最新内容）")
            .AppendLine()
            .AppendLine("【左栏：贴图 + UV 预览】")
            .AppendLine("· 预览下方工具按「视图 / 选择 / 顶点同步」分组，默认折叠成一行胶囊开关，点哪个展开哪个（状态记在插件目录 ui.json）。选面与平移是独立按钮，蓝色表示当前模式。大量顶点以合并标记显示，选择数据与发送顶点不减少。")
            .AppendLine("· 滚轮：以光标为中心缩放；右键拖动：任何模式下都可平移")
            .AppendLine("· 单击：点选单个 UV 三角面（Shift 加选 / Ctrl 减选 / 再点一次取消）")
            .AppendLine("· 双击：加选「整块连通 UV 岛」（类 Blender 按 L 的手感）；继续双击别的块可同时选多块，再双击一次取消该块（Ctrl+双击 = 强制取消）")
            .AppendLine("· 左键拖动：选面模式下 = 框选 UV 三角面；平移模式下 = 平移视图")
            .AppendLine("· 「选连通块」按钮：把当前选区补成完整的连通 UV 块（选区涉及到的每一块都会补全，且不会清掉已有选区）")
            .AppendLine("· 选中面的顶点会以红色标识显示；「从模型接收」读取 3D 视图选中顶点并标红，")
            .AppendLine("  「发送到模型」把标红顶点设为 3D 视图的选中顶点（与 PMXEditor 双向互通）")
            .AppendLine("· 「对比原图」按钮：切换显示原贴图 / 调色结果（参数不受影响）")
            .AppendLine("· 预览下方「视图」组的「隐藏 UV / 显示 UV」切换线框和顶点标记，并与顶部菜单同步；选区及调色结果保留。")
            .AppendLine("· 直方图：RGB 叠加，实时反映当前预览（默认关闭，视图菜单可开）")
            .AppendLine("· 调色范围：默认「UV 选区优先」，有选区时仅改变选区内像素；没有选区时调整整张贴图。选择「整张贴图」后会适配显示全图，暂时忽略但保留 UV 选区，其他共用贴图的材质 UV 显示为灰线。")
            .AppendLine("· 整图调色也会改变当前材质选中顶点对应区域以外的像素；左栏会提示共用贴图的材质数量。刷新模型或另存仍仅更新当前材质的贴图引用，不会自动替换其他材质的贴图。调色范围支持撤销、预设和分材质记忆。")
            .AppendLine()
            .AppendLine("【右栏：材质与调整】")
            .AppendLine("· 材质列表：贴图缩略图 + 序号·名称，「已修改」表示该材质已改过参数或已推送到模型")
            .AppendLine("· 预设 / 收藏：把调好的参数存成 JSON 预设，一键套用到其它材质（双击预设即应用）")
            .AppendLine("· 调整：折叠组（基本 / 色彩 / HSL 分通道 / 曲线色阶RGB HSV / 细节 / 效果）")
            .AppendLine("· 每个材质的调色参数会分别记住，来回切材质不会丢")
            .AppendLine()
            .AppendLine("【效果：黑白化与阈值】")
            .AppendLine("· 阈值强度 0% 为关闭，100% 得到纯黑白块。黑白分界值可在 0–255 之间拖动或输入，默认 127.5；亮度低于分界变黑，达到分界变白。数值越大，黑色区域越多。")
            .AppendLine("· 黑白化按加权亮度将颜色转为连续灰阶，滑块控制混合比例：0 保留原色，100 完全黑白化。浅灰横线下方为阈值强度和黑白分界值。")
            .AppendLine()
            .AppendLine("【文件菜单】")
            .AppendLine("· 导出 UV 布局图…：透明背景 + 线框的 PNG（尺寸同贴图，可直接叠在贴图上对齐）")
            .AppendLine("· 导出当前选区蒙版…：把左栏选中的 UV 面导成黑白 PNG（白 = 选中）")
            .AppendLine("· 导出当前材质蒙版…：把当前材质全部 UV 面导成黑白 PNG（白 = 该材质）")
            .AppendLine("· 导出全部材质蒙版…：每个材质导一张（白 = 该材质的 UV 覆盖区域）")
            .AppendLine("· 打开预设文件夹：预设存放位置见 presets 文件夹")
            .AppendLine()
            .AppendLine("【底部按钮】")
            .AppendLine("· 重新读取：重新从 PMX 读取材质与贴图")
            .AppendLine("· 刷新模型：把当前调色结果写临时贴图并推送到 3D 视图（原图不动）")
            .AppendLine("· 另存为新贴图：选择格式、尺寸与 JPEG 质量后保存并更新材质引用；文件菜单保留快速另存为 PNG。支持 PNG/JPEG/BMP/GIF/TIFF/TGA/DDS（Raw/DXT1/3/5）。")
            .AppendLine("· 切换材质或重新读取会保留 UV 选区和接收顶点；几何/UV 改变时不恢复旧选区。左侧或编辑菜单可反选（Ctrl+I），Ctrl+A 全选，文本框除外。")
            .AppendLine("· 预设支持改名、名称/时间/手动排序及上移/下移，顺序与排序方式会保存。")
            .AppendLine("· 文件菜单可导出选区 Alpha PNG：RGB 选白色/原图/调色结果，Alpha 替换为选中 255、其余 0。整图调色时仍按显式 UV 选区导出，不修改原贴图或模型引用。")
            .AppendLine("· 另存优先写入相对于当前 PMX 目录的贴图路径；未保存模型或跨盘时使用绝对路径。关闭插件会先恢复正式贴图引用，再清理临时预览，已另存的贴图保留。")
            .AppendLine("· 还原 / 重置参数 / 撤销 / 重做")
            .AppendLine()
            .AppendLine("【非破坏式流程】")
            .AppendLine("滑块只改内存里的预览，不会动原贴图文件。")
            .AppendLine("确认满意后用「刷新模型」看 3D 效果，或用「另存为新贴图」落盘。")
            .AppendLine("「还原」把材质的 Material.Tex 恢复到原始值并清理临时文件。")
            .AppendLine()
            .AppendLine("【说明文件在哪】")
            .AppendLine("· 本文件在插件目录下的 data 文件夹：data\\TextureGrade_Operation_SC.txt")
            .AppendLine("· 四种语言各一份：_EN（English）/ _SC（简体中文）/ _TC（繁體中文）/ _JP（日本語）")
            .AppendLine("· 插件启动时若发现缺失会自动补生成，已存在的文件不会被覆盖")
            .AppendLine("· 切换界面语言时说明窗口自动改读对应那份；直接编辑 txt 后点「重新载入」即可")
            .ToString();

        private static string ZhTw() => new StringBuilder()
            .AppendLine("Texture Grade — 操作說明")
            .AppendLine("（本檔案由外掛自動產生，可自由編輯；改完在說明視窗點「重新載入」即可看到最新內容）")
            .AppendLine()
            .AppendLine("【左欄：貼圖 + UV 預覽】")
            .AppendLine("· 滾輪：以游標為中心縮放；右鍵拖曳：任何模式下都可平移")
            .AppendLine("· 單擊：點選單一 UV 三角面（Shift 加選 / Ctrl 減選 / 再點一次取消）")
            .AppendLine("· 雙擊：加選「整塊連通 UV 島」（類 Blender 按 L 的手感）；繼續雙擊別的塊可同時選多塊，再雙擊一次取消該塊（Ctrl+雙擊 = 強制取消）")
            .AppendLine("· 左鍵拖曳：選面模式下 = 框選 UV 三角面；平移模式下 = 平移檢視")
            .AppendLine("· 「選連通塊」按鈕：把目前選取補成完整的連通 UV 塊（選取涉及到的每一塊都會補全，且不會清掉已有選取）")
            .AppendLine("· 預覽下方工具依「檢視 / 選取 / 頂點同步」分組，預設折疊成一行膠囊開關，點哪個展開哪個（狀態記在外掛目錄 ui.json）。選面與平移為獨立按鈕，藍色表示目前模式。大量頂點以合併標記顯示，不減少選取資料或傳送頂點。")
            .AppendLine("· 選取面的頂點會以紅色標識顯示；「從模型接收」讀取 3D 視圖選取頂點並標紅，")
            .AppendLine("  「傳送到模型」把標紅頂點設為 3D 視圖的選取頂點（與 PMXEditor 雙向互通）")
            .AppendLine("· 「對比原圖」按鈕：切換顯示原貼圖 / 調色結果（參數不受影響）")
            .AppendLine("· 預覽下方「檢視」組的「隱藏 UV / 顯示 UV」切換線框和頂點標記，並與頂端選單同步；選取範圍及調色結果保留。")
            .AppendLine("· 直方圖：RGB 疊加，即時反映目前預覽（預設關閉，檢視選單可開）")
            .AppendLine("· 調色範圍：預設「UV 選區優先」，有選區時僅改變選區內像素；沒有選區時調整整張貼圖。選擇「整張貼圖」後會適配顯示全圖，暫時忽略但保留 UV 選區，其他共用貼圖的材質 UV 顯示為灰線。")
            .AppendLine("· 整圖調色也會改變目前材質所選頂點對應區域以外的像素；左欄會提示共用貼圖的材質數量。刷新模型或另存仍僅更新目前材質的貼圖參照，不會自動替換其他材質的貼圖。調色範圍支援復原、預設集和分材質記憶。")
            .AppendLine()
            .AppendLine("【右欄：材質與調整】")
            .AppendLine("· 材質清單：貼圖縮圖 + 序號·名稱，「已修改」表示該材質已改過參數或已推送到模型")
            .AppendLine("· 預設 / 收藏：把調好的參數存成 JSON 預設，一鍵套用到其它材質（雙擊預設即套用）")
            .AppendLine("· 調整：摺疊組（基本 / 色彩 / HSL 分通道 / 曲線色階RGB HSV / 細節 / 效果）")
            .AppendLine("· 每個材質的調色參數會分別記住，來回切材質不會遺失")
            .AppendLine()
            .AppendLine("【效果：黑白化與閾值】")
            .AppendLine("· 閾值強度 0% 為關閉，100% 得到純黑白塊。黑白分界值可在 0–255 之間拖曳或輸入，預設 127.5；亮度低於分界變黑，達到分界變白。數值越大，黑色區域越多。")
            .AppendLine("· 黑白化依加權亮度將色彩轉為連續灰階，滑桿控制混合比例：0 保留原色，100 完全黑白化。淺灰橫線下方為閾值強度和黑白分界值。")
            .AppendLine()
            .AppendLine("【檔案選單】")
            .AppendLine("· 匯出 UV 佈局圖…：透明背景 + 線框的 PNG（尺寸同貼圖，可直接疊在貼圖上對齊）")
            .AppendLine("· 匯出目前選取遮罩…：把左欄選中的 UV 面匯成黑白 PNG（白 = 選取）")
            .AppendLine("· 匯出目前材質遮罩…：把目前材質全部 UV 面匯成黑白 PNG（白 = 該材質）")
            .AppendLine("· 匯出全部材質遮罩…：每個材質匯出一張（白 = 該材質的 UV 覆蓋區域）")
            .AppendLine("· 開啟預設資料夾：預設存放位置見 presets 資料夾")
            .AppendLine()
            .AppendLine("【底部按鈕】")
            .AppendLine("· 重新讀取：重新從 PMX 讀取材質與貼圖")
            .AppendLine("· 刷新模型：把目前調色結果寫暫存貼圖並推送到 3D 檢視（原圖不動）")
            .AppendLine("· 另存為新貼圖：選擇格式、尺寸與 JPEG 品質後儲存並更新材質參照；檔案選單保留快速 PNG 儲存。支援 PNG/JPEG/BMP/GIF/TIFF/TGA/DDS（Raw/DXT1/3/5）。")
            .AppendLine("· 切換材質或重新讀取會保留 UV 選區和接收頂點；幾何/UV 改變時不恢復舊選區。左側或編輯選單可反選（Ctrl+I），Ctrl+A 全選，文字框除外。")
            .AppendLine("· 預設集支援改名、名稱/時間/手動排序及上移/下移，順序與排序方式會儲存。")
            .AppendLine("· 檔案選單可匯出選區 Alpha PNG：RGB 選白色/原圖/調色結果，Alpha 取代為選取 255、其餘 0。整圖調色時仍依明確 UV 選區匯出，不修改原貼圖或模型參照。")
            .AppendLine("· 另存優先寫入相對於目前 PMX 目錄的貼圖路徑；未儲存模型或跨磁碟時使用絕對路徑。關閉外掛會先恢復正式貼圖參照，再清理暫存預覽，已另存的貼圖保留。")
            .AppendLine("· 還原 / 重設參數 / 復原 / 重做")
            .AppendLine()
            .AppendLine("【非破壞式流程】")
            .AppendLine("滑桿只改記憶體裡的預覽，不會動原貼圖檔案。")
            .AppendLine("確認滿意後用「刷新模型」看 3D 效果，或用「另存為新貼圖」落盤。")
            .AppendLine("「還原」把材質的 Material.Tex 恢復到原始值並清理暫存檔。")
            .AppendLine()
            .AppendLine("【說明檔案在哪】")
            .AppendLine("· 本檔案在外掛目錄下的 data 資料夾：data\\TextureGrade_Operation_TC.txt")
            .AppendLine("· 四種語言各一份：_EN（English）/ _SC（简体中文）/ _TC（繁體中文）/ _JP（日本語）")
            .AppendLine("· 外掛啟動時若發現缺失會自動補產生，已存在的檔案不會被覆寫")
            .AppendLine("· 切換介面語言時說明視窗自動改讀對應那份；直接編輯 txt 後點「重新載入」即可")
            .ToString();

        private static string En() => new StringBuilder()
            .AppendLine("Texture Grade — Operation Manual")
            .AppendLine("(This file was generated by the plug-in. Edit it freely, then click Reload in the manual window.)")
            .AppendLine()
            .AppendLine("[Left panel: texture + UV preview]")
            .AppendLine("- Wheel: zoom around the cursor.  Right-drag: pan in any mode.")
            .AppendLine("- Click: pick a single UV triangle (Shift = add, Ctrl = subtract, click again = deselect).")
            .AppendLine("- Double-click: add the whole connected UV island (like pressing L in Blender). Keep double-clicking other islands to select several at once; double-click one again (or Ctrl+double-click) to remove it.")
            .AppendLine("- Left-drag: box-select UV faces in Select mode, or pan the view in Pan mode.")
            .AppendLine("- \"Select Island\" button: grow the current selection into complete connected islands — every island the selection touches is completed, and the existing selection is kept.")
            .AppendLine("- Tools under the preview are grouped as View / Selection / Vertices and fold into one row of chips; click a chip to expand that group (all collapsed by default, state saved in ui.json next to the plug-in). Select and Pan have separate buttons; blue indicates the active mode. Dense display marks are combined without reducing selected or sent vertices.")
            .AppendLine("- Vertices of selected faces are shown as red marks; \"From Model\" reads the 3D view's selected vertices and marks them red,")
            .AppendLine("  \"To Model\" pushes the red-marked vertices back to the 3D view as its selection (two-way with PMXEditor).")
            .AppendLine("- \"Compare Original\" button: toggle between the original texture and the graded result (parameters are kept).")
            .AppendLine("- Hide UV / Show UV in the View group under the preview toggles wireframes and vertex markers, synchronized with the top menu. Selection and graded pixels are preserved.")
            .AppendLine("- Histogram: overlaid RGB, updated live (hidden by default; toggle from the View menu).")
            .AppendLine("- Grading scope defaults to UV selection first: only selected pixels change when a selection exists; otherwise the whole texture changes. Whole texture fits the image in view and temporarily ignores, but retains, the selection. Gray UV lines show other materials using the same texture.")
            .AppendLine("- Whole-texture grading changes pixels outside the current material's selected vertices as well. The left panel shows how many materials share the texture. Refresh and Save as New still update only the current material's texture reference. Scope is included in undo, presets and per-material settings.")
            .AppendLine()
            .AppendLine("[Right panel: materials and adjustments]")
            .AppendLine("- Material list: texture thumbnail + index - name. \"Modified\" means parameters changed or pushed to the model.")
            .AppendLine("- Presets / Favorites: save the current parameters as a JSON preset and apply it elsewhere (double-click to apply).")
            .AppendLine("- Adjust: collapsible groups (Basic / Color / HSL per channel / Curves,Levels,RGB,HSV / Detail / Effects).")
            .AppendLine("- Parameters are remembered per material, so switching back and forth loses nothing.")
            .AppendLine()
            .AppendLine("[Effects: grayscale and threshold]")
            .AppendLine("- Threshold mix: 0% disables the effect; 100% creates solid black/white regions. Drag or type a level from 0–255 (default 127.5): brightness below it becomes black, at or above it becomes white. Higher values expand black regions.")
            .AppendLine("- Grayscale blends colors toward weighted brightness while preserving continuous gray tones: 0 keeps the original colors, 100 is fully grayscale. The threshold mix and level sit below the light gray divider.")
            .AppendLine()
            .AppendLine("[File menu]")
            .AppendLine("- Export UV Layout…: transparent PNG with wireframe, same size as the texture, so it aligns over it.")
            .AppendLine("- Export Selection Mask…: black/white PNG of the selected UV faces (white = selected).")
            .AppendLine("- Export Current Material Mask…: black/white PNG of every UV face of the current material (white = this material).")
            .AppendLine("- Export All Material Masks…: one PNG per material (white = that material's UV area).")
            .AppendLine("- Open Preset Folder: opens the presets folder.")
            .AppendLine()
            .AppendLine("[Bottom buttons]")
            .AppendLine("- Re-read: reload materials and textures from the PMX.")
            .AppendLine("- Refresh Model: write the graded result to a temp texture and push it to the 3D view (original untouched).")
            .AppendLine("- Save as New Texture: choose format, size and JPEG quality, then save and update the material reference. File also offers quick PNG saving. Formats: PNG/JPEG/BMP/GIF/TIFF/TGA/DDS (Raw/DXT1/3/5).")
            .AppendLine("- Material switching/re-reading retains UV selection and received vertices unless geometry/UVs changed. Invert from the left toolbar or Edit menu (Ctrl+I); Ctrl+A selects all. Text boxes keep their shortcuts.")
            .AppendLine("- Presets support rename, name/time/custom sorting and Move Up/Down; order and sort mode persist.")
            .AppendLine("- File can export selection-alpha PNG: RGB contains white/original/graded pixels; alpha is replaced with selected=255, other=0. This uses the explicit UV selection even during whole-texture grading, without changing the source texture or model reference.")
            .AppendLine("- Saved textures use a path relative to the current PMX folder where possible; unsaved models or different drives use absolute paths. Closing the plug-in restores the permanent texture reference before deleting temporary previews. Saved textures are kept.")
            .AppendLine("- Revert / Reset Parameters / Undo / Redo.")
            .AppendLine()
            .AppendLine("[Non-destructive workflow]")
            .AppendLine("Sliders only change the in-memory preview; the original texture file is never touched.")
            .AppendLine("Use Refresh Model to preview in 3D, or Save as New Texture to write it to disk.")
            .AppendLine("Revert restores Material.Tex to its original value and cleans up temp files.")
            .AppendLine()
            .AppendLine("[Where the manual lives]")
            .AppendLine("- This file sits in the data folder next to the plug-in: data\\TextureGrade_Operation_EN.txt")
            .AppendLine("- One file per language: _EN / _SC (Simplified Chinese) / _TC (Traditional Chinese) / _JP (Japanese).")
            .AppendLine("- Missing files are generated automatically at start-up; existing ones are never overwritten.")
            .AppendLine("- Switching the UI language switches which file is read; edit the txt and click Reload to refresh.")
            .ToString();

        private static string Ja() => new StringBuilder()
            .AppendLine("Texture Grade — 操作説明")
            .AppendLine("（このファイルはプラグインが自動生成しました。自由に編集し、説明ウィンドウの「再読み込み」で反映できます）")
            .AppendLine()
            .AppendLine("【左パネル：テクスチャ + UV プレビュー】")
            .AppendLine("· ホイール：カーソル中心にズーム。右ドラッグ：どのモードでも平移。")
            .AppendLine("· クリック：UV 三角面を 1 枚選択（Shift で追加 / Ctrl で削除 / もう一度クリックで解除）")
            .AppendLine("· ダブルクリック：連結した UV アイランドをまとめて追加選択（Blender の L キー相当）。続けて別のアイランドをダブルクリックすれば複数同時選択、もう一度ダブルクリック（または Ctrl+ダブルクリック）で解除")
            .AppendLine("· 左ドラッグ：選択モードでは矩形選択、平移モードでは表示を移動")
            .AppendLine("· 「アイランド選択」ボタン：現在の選択を完全な連結アイランドに拡張（選択が触れているすべてのアイランドを補完し、既存の選択は消しません）")
            .AppendLine("· プレビュー下のツールは表示 / 選択 / 頂点同期に分類され、既定では 1 行のチップに折りたたまれています（クリックした組だけ展開、状態は ui.json に保存）。選択と平移は独立したボタンで、青色が現在のモードです。密集した表示マークは統合しますが、選択や送信する頂点は減らしません。")
            .AppendLine("· 選択面の頂点は赤く表示されます。「モデルから受信」で3Dビューの選択頂点を読み込んで赤表示、")
            .AppendLine("  「モデルへ送信」で赤表示中の頂点を3Dビューの選択として送信（PMXエディタと双方向）")
            .AppendLine("· 「元画像比較」ボタン：元テクスチャと調整結果を切り替え（パラメータは保持）")
            .AppendLine("· プレビュー下の表示グループの「UV を隠す / UV を表示」で線と頂点マーカーを切り替え、上部メニューと同期します。選択範囲と調色結果は保持されます。")
            .AppendLine("· ヒストグラム：RGB 重ね合わせ、リアルタイム更新（既定では非表示、表示メニューで切替）")
            .AppendLine("· 調色範囲の既定は UV 選択優先です。選択があればその範囲のみ、なければ画像全体を調整します。「テクスチャ全体」では全体を表示し、選択を保持したまま一時的に無視します。同じ画像を使用する他材質の UV は灰色で表示します。")
            .AppendLine("· 全体の調色は現在の材質の選択頂点に対応する領域外の画素も変更します。左パネルに画像を共有する材質数を表示します。更新と新規保存で参照先が変わるのは現在の材質だけです。範囲は取り消し、プリセット、材質ごとの設定に保存されます。")
            .AppendLine()
            .AppendLine("【右パネル：材質と調整】")
            .AppendLine("· 材質一覧：サムネイル + 番号·名称。「変更済み」は調整済みまたはモデルへ反映済み")
            .AppendLine("· プリセット / お気に入り：調整値を JSON で保存し、他材質へワンクリック適用（ダブルクリックで適用）")
            .AppendLine("· 調整：折りたたみグループ（基本 / カラー / HSL / カーブ·レベル·RGB·HSV / ディテール / エフェクト）")
            .AppendLine("· パラメータは材質ごとに記憶され、切り替えても失われません")
            .AppendLine()
            .AppendLine("【エフェクト：白黒化と2 値化】")
            .AppendLine("· 2 値化の強度は 0% で無効、100% で白黒の領域になります。境界値は 0–255（既定 127.5）を入力またはドラッグで指定します。境界未満は黒、以上は白になり、大きくすると黒い領域が増えます。")
            .AppendLine("· 白黒化は色を加重した明るさに変換し、連続した階調を保ちます。0 は元の色、100 は完全な白黒です。薄いグレーの区切り線の下に2 値化の強度と境界値を配置しています。")
            .AppendLine()
            .AppendLine("【ファイルメニュー】")
            .AppendLine("· UV レイアウトを書き出し…：透明背景 + ワイヤーフレームの PNG（テクスチャと同サイズで重ねられます）")
            .AppendLine("· 選択範囲マスクを書き出し…：選択した UV 面の白黒 PNG（白 = 選択）")
            .AppendLine("· 現在の材質マスクを書き出し…：現在の材質の全 UV 面の白黒 PNG（白 = その材質）")
            .AppendLine("· 全材質マスクを書き出し…：材質ごとに 1 枚（白 = その材質の UV 領域）")
            .AppendLine("· プリセットフォルダを開く：presets フォルダを開きます")
            .AppendLine()
            .AppendLine("【下部ボタン】")
            .AppendLine("· 再読み込み：PMX から材質とテクスチャを再取得")
            .AppendLine("· モデルを更新：調整結果を一時テクスチャに書き出し 3D ビューへ反映（元画像は不変）")
            .AppendLine("· 新規保存：形式、サイズ、JPEG 品質を選択して材質の参照先を更新します。ファイルメニューにはクイック PNG 保存もあります。形式：PNG/JPEG/BMP/GIF/TIFF/TGA/DDS（Raw/DXT1/3/5）。")
            .AppendLine("· 材質切替・再読込は UV 選択と受信頂点を保持します。形状/UV 変更時は旧選択を破棄します。左ツール・編集メニューで反転（Ctrl+I）、Ctrl+A で全選択。文字入力時は除きます。")
            .AppendLine("· プリセットは名前変更、名前/更新日時/手動順と上下移動に対応し、順序と並び替え方法を保存します。")
            .AppendLine("· 選択 Alpha PNG を出力できます。RGB は白/元画像/調整結果、Alpha は選択=255・その他=0 に置換します。画像全体モードでも明示的な UV 選択を使用し、元画像やモデル参照は変更しません。")
            .AppendLine("· 保存時は現在の PMX フォルダーからの相対パスを優先します。モデルが未保存、または別ドライブの場合は絶対パスです。終了時は保存済みの参照先を復元してから一時プレビューを削除し、保存したテクスチャは残します。")
            .AppendLine("· 元に戻す / パラメータリセット / 取り消し / やり直し")
            .AppendLine()
            .AppendLine("【非破壊ワークフロー】")
            .AppendLine("スライダーはメモリ上のプレビューを変更するだけで、元テクスチャは書き換えません。")
            .AppendLine("3D で確認するなら「モデルを更新」、保存するなら「新規テクスチャに保存」を使います。")
            .AppendLine("「元に戻す」で Material.Tex を元の値に復元し、一時ファイルを削除します。")
            .AppendLine()
            .AppendLine("【説明ファイルの場所】")
            .AppendLine("· このファイルはプラグイン配下の data フォルダにあります：data\\TextureGrade_Operation_JP.txt")
            .AppendLine("· 4 言語ぶん：_EN（English）/ _SC（简体中文）/ _TC（繁體中文）/ _JP（日本語）")
            .AppendLine("· 起動時に不足分は自動生成され、既存ファイルは上書きされません")
            .AppendLine("· 表示言語を切り替えると対応ファイルを読み直します。txt を編集したら「再読み込み」を押してください")
            .ToString();
    }
}
