using System.Text;

namespace TextureGrade.Localization
{
    /// <summary>
    /// 内置的操作说明正文。
    /// 用途：插件同级目录下没有 TextureGrade_Operation.txt 时，按当前语言生成一份默认文件，
    /// 用户之后直接改那个 txt 即可（改完点窗口里的「重新载入」）。
    /// </summary>
    public static class DefaultManual
    {
        public static string Get(Lang l)
        {
            switch (l)
            {
                case Lang.ZhCn: return ZhCn();
                case Lang.ZhTw: return ZhTw();
                case Lang.Ja: return Ja();
                default: return En();
            }
        }

        private static string ZhCn() => new StringBuilder()
            .AppendLine("Texture Grade — 操作说明")
            .AppendLine("（本文件由插件自动生成，可随意编辑；改完在说明窗口点「重新载入」即可看到最新内容）")
            .AppendLine()
            .AppendLine("【左栏：贴图 + UV 预览】")
            .AppendLine("· 滚轮：以光标为中心缩放；右键拖动：任何模式下都可平移")
            .AppendLine("· 单击：点选单个 UV 三角面（Shift 加选 / Ctrl 减选 / 再点一次取消）")
            .AppendLine("· 双击：加选「整块连通 UV 岛」（类 Blender 按 L 的手感）；继续双击别的块可同时选多块，再双击一次取消该块（Ctrl+双击 = 强制取消）")
            .AppendLine("· 左键拖动：选面模式下 = 框选 UV 三角面；平移模式下 = 平移视图")
            .AppendLine("· 「选连通块」按钮：把当前选区补成完整的连通 UV 块（选区涉及到的每一块都会补全，且不会清掉已有选区）")
            .AppendLine("· 「对比原图」按钮：切换显示原贴图 / 调色结果（参数不受影响）")
            .AppendLine("· 直方图：RGB 叠加，实时反映当前预览（视图菜单可关闭）")
            .AppendLine("· 选中后调色只作用于选区，选区外保持原贴图")
            .AppendLine()
            .AppendLine("【右栏：材质与调整】")
            .AppendLine("· 材质列表：贴图缩略图 + 序号·名称，「已修改」表示该材质已改过参数或已推送到模型")
            .AppendLine("· 预设 / 收藏：把调好的参数存成 JSON 预设，一键套用到其它材质（双击预设即应用）")
            .AppendLine("· 调整：折叠组（基本 / 色彩 / Lab 取色环 / HSL 分通道 / 曲线色阶RGB HSV / 细节 / 效果）")
            .AppendLine("· 每个材质的调色参数会分别记住，来回切材质不会丢")
            .AppendLine()
            .AppendLine("【Lab 取色环（亮度锁定）】")
            .AppendLine("· 外环 = 色相、内圈 = 彩度；环上的颜色全部是同一个亮度 L*（等亮度色相环）")
            .AppendLine("· 勾选「锁定亮度 L*」后，取任何颜色都只改色相/彩度，画面每个像素自身的亮度一动不动")
            .AppendLine("· 取消勾选则连亮度一起朝目标色靠拢")
            .AppendLine("· 「取画面亮度」把色环锚定到当前选区（无选区则整张图）的平均亮度 L*")
            .AppendLine("· 「取画面色相」以画面原色为起点，再在环上微调；「强度」控制生效比例")
            .AppendLine()
            .AppendLine("【文件菜单】")
            .AppendLine("· 导出 UV 布局图…：透明背景 + 线框的 PNG（尺寸同贴图，可直接叠在贴图上对齐）")
            .AppendLine("· 导出当前选区蒙版…：把左栏选中的 UV 面导成黑白 PNG（白 = 选中）")
            .AppendLine("· 导出当前材质蒙版…：把当前材质全部 UV 面导成黑白 PNG（白 = 该材质）")
            .AppendLine("· 导出全部材质蒙版…：每个材质导一张（白 = 该材质的 UV 覆盖区域）")
            .AppendLine("· 打开预设文件夹：预设存放位置见 presets 文件夹")
            .AppendLine()
            .AppendLine("【底部按钮】")
            .AppendLine("· 重新读取：重新从 PMX 读取材质与贴图")
            .AppendLine("· 刷新模型：把当前调色结果写临时贴图并推送到 3D 视图（原图不动）")
            .AppendLine("· 另存为新贴图：写 xxx_new.png 并让材质指向它")
            .AppendLine("· 还原 / 重置参数 / 撤销 / 重做")
            .AppendLine()
            .AppendLine("【非破坏式流程】")
            .AppendLine("滑块只改内存里的预览，不会动原贴图文件。")
            .AppendLine("确认满意后用「刷新模型」看 3D 效果，或用「另存为新贴图」落盘。")
            .AppendLine("「还原」把材质的 Material.Tex 恢复到原始值并清理临时文件。")
            .AppendLine()
            .AppendLine("【说明文件在哪】")
            .AppendLine("· 本文件在插件目录下的 data 文件夹：data\\TextureGrade_Operation_SC.txt")
            .AppendLine("· 四种语言各一份：_EN（English）/ _SC（简体中文）/ _TC（繁體中文）/ _JP（日本語）")
            .AppendLine("· 插件启动时若发现缺失会自动补生成，已存在的文件不会被覆盖")
            .AppendLine("· 切换界面语言时说明窗口自动改读对应那份；直接编辑 txt 后点「重新载入」即可")
            .ToString();

        private static string ZhTw() => new StringBuilder()
            .AppendLine("Texture Grade — 操作說明")
            .AppendLine("（本檔案由外掛自動產生，可自由編輯；改完在說明視窗點「重新載入」即可看到最新內容）")
            .AppendLine()
            .AppendLine("【左欄：貼圖 + UV 預覽】")
            .AppendLine("· 滾輪：以游標為中心縮放；右鍵拖曳：任何模式下都可平移")
            .AppendLine("· 單擊：點選單一 UV 三角面（Shift 加選 / Ctrl 減選 / 再點一次取消）")
            .AppendLine("· 雙擊：加選「整塊連通 UV 島」（類 Blender 按 L 的手感）；繼續雙擊別的塊可同時選多塊，再雙擊一次取消該塊（Ctrl+雙擊 = 強制取消）")
            .AppendLine("· 左鍵拖曳：選面模式下 = 框選 UV 三角面；平移模式下 = 平移檢視")
            .AppendLine("· 「選連通塊」按鈕：把目前選取補成完整的連通 UV 塊（選取涉及到的每一塊都會補全，且不會清掉已有選取）")
            .AppendLine("· 「對比原圖」按鈕：切換顯示原貼圖 / 調色結果（參數不受影響）")
            .AppendLine("· 直方圖：RGB 疊加，即時反映目前預覽（檢視選單可關閉）")
            .AppendLine("· 選取後調色只作用於選取範圍，選取外保持原貼圖")
            .AppendLine()
            .AppendLine("【右欄：材質與調整】")
            .AppendLine("· 材質清單：貼圖縮圖 + 序號·名稱，「已修改」表示該材質已改過參數或已推送到模型")
            .AppendLine("· 預設 / 收藏：把調好的參數存成 JSON 預設，一鍵套用到其它材質（雙擊預設即套用）")
            .AppendLine("· 調整：摺疊組（基本 / 色彩 / Lab 取色環 / HSL 分通道 / 曲線色階RGB HSV / 細節 / 效果）")
            .AppendLine("· 每個材質的調色參數會分別記住，來回切材質不會遺失")
            .AppendLine()
            .AppendLine("【Lab 取色環（亮度鎖定）】")
            .AppendLine("· 外環 = 色相、內圈 = 彩度；環上的顏色全部是同一個亮度 L*（等亮度色相環）")
            .AppendLine("· 勾選「鎖定亮度 L*」後，取任何顏色都只改色相/彩度，畫面每個像素自身的亮度一動不動")
            .AppendLine("· 取消勾選則連亮度一起朝目標色靠攏")
            .AppendLine("· 「取畫面亮度」把色環錨定到目前選取（無選取則整張圖）的平均亮度 L*")
            .AppendLine("· 「取畫面色相」以畫面原色為起點，再在環上微調；「強度」控制生效比例")
            .AppendLine()
            .AppendLine("【檔案選單】")
            .AppendLine("· 匯出 UV 佈局圖…：透明背景 + 線框的 PNG（尺寸同貼圖，可直接疊在貼圖上對齊）")
            .AppendLine("· 匯出目前選取遮罩…：把左欄選中的 UV 面匯成黑白 PNG（白 = 選取）")
            .AppendLine("· 匯出目前材質遮罩…：把目前材質全部 UV 面匯成黑白 PNG（白 = 該材質）")
            .AppendLine("· 匯出全部材質遮罩…：每個材質匯出一張（白 = 該材質的 UV 覆蓋區域）")
            .AppendLine("· 開啟預設資料夾：預設存放位置見 presets 資料夾")
            .AppendLine()
            .AppendLine("【底部按鈕】")
            .AppendLine("· 重新讀取：重新從 PMX 讀取材質與貼圖")
            .AppendLine("· 刷新模型：把目前調色結果寫暫存貼圖並推送到 3D 檢視（原圖不動）")
            .AppendLine("· 另存為新貼圖：寫 xxx_new.png 並讓材質指向它")
            .AppendLine("· 還原 / 重設參數 / 復原 / 重做")
            .AppendLine()
            .AppendLine("【非破壞式流程】")
            .AppendLine("滑桿只改記憶體裡的預覽，不會動原貼圖檔案。")
            .AppendLine("確認滿意後用「刷新模型」看 3D 效果，或用「另存為新貼圖」落盤。")
            .AppendLine("「還原」把材質的 Material.Tex 恢復到原始值並清理暫存檔。")
            .AppendLine()
            .AppendLine("【說明檔案在哪】")
            .AppendLine("· 本檔案在外掛目錄下的 data 資料夾：data\\TextureGrade_Operation_TC.txt")
            .AppendLine("· 四種語言各一份：_EN（English）/ _SC（简体中文）/ _TC（繁體中文）/ _JP（日本語）")
            .AppendLine("· 外掛啟動時若發現缺失會自動補產生，已存在的檔案不會被覆寫")
            .AppendLine("· 切換介面語言時說明視窗自動改讀對應那份；直接編輯 txt 後點「重新載入」即可")
            .ToString();

        private static string En() => new StringBuilder()
            .AppendLine("Texture Grade — Operation Manual")
            .AppendLine("(This file was generated by the plug-in. Edit it freely, then click Reload in the manual window.)")
            .AppendLine()
            .AppendLine("[Left panel: texture + UV preview]")
            .AppendLine("- Wheel: zoom around the cursor.  Right-drag: pan in any mode.")
            .AppendLine("- Click: pick a single UV triangle (Shift = add, Ctrl = subtract, click again = deselect).")
            .AppendLine("- Double-click: add the whole connected UV island (like pressing L in Blender). Keep double-clicking other islands to select several at once; double-click one again (or Ctrl+double-click) to remove it.")
            .AppendLine("- Left-drag: box-select UV faces in Select mode, or pan the view in Pan mode.")
            .AppendLine("- \"Select Island\" button: grow the current selection into complete connected islands — every island the selection touches is completed, and the existing selection is kept.")
            .AppendLine("- \"Compare Original\" button: toggle between the original texture and the graded result (parameters are kept).")
            .AppendLine("- Histogram: overlaid RGB, updated live (can be hidden from the View menu).")
            .AppendLine("- Grading only affects the selection; everything outside keeps the original pixels.")
            .AppendLine()
            .AppendLine("[Right panel: materials and adjustments]")
            .AppendLine("- Material list: texture thumbnail + index - name. \"Modified\" means parameters changed or pushed to the model.")
            .AppendLine("- Presets / Favorites: save the current parameters as a JSON preset and apply it elsewhere (double-click to apply).")
            .AppendLine("- Adjust: collapsible groups (Basic / Color / Lab wheel / HSL per channel / Curves,Levels,RGB,HSV / Detail / Effects).")
            .AppendLine("- Parameters are remembered per material, so switching back and forth loses nothing.")
            .AppendLine()
            .AppendLine("[Lab color wheel (lightness locked)]")
            .AppendLine("- Outer ring = hue, inner disc = chroma. Every color on the ring sits at the same lightness L*.")
            .AppendLine("- With \"Lock lightness L*\" checked, any color you pick only changes hue/chroma; each pixel keeps its own L*.")
            .AppendLine("- Uncheck it to let lightness move toward the target color as well.")
            .AppendLine("- \"Pick Image Lightness\" anchors the wheel to the average L* of the selection (or the whole image).")
            .AppendLine("- \"Pick Image Hue\" starts from the image's own color; \"Amount\" controls how strongly it applies.")
            .AppendLine()
            .AppendLine("[File menu]")
            .AppendLine("- Export UV Layout…: transparent PNG with wireframe, same size as the texture, so it aligns over it.")
            .AppendLine("- Export Selection Mask…: black/white PNG of the selected UV faces (white = selected).")
            .AppendLine("- Export Current Material Mask…: black/white PNG of every UV face of the current material (white = this material).")
            .AppendLine("- Export All Material Masks…: one PNG per material (white = that material's UV area).")
            .AppendLine("- Open Preset Folder: opens the presets folder.")
            .AppendLine()
            .AppendLine("[Bottom buttons]")
            .AppendLine("- Re-read: reload materials and textures from the PMX.")
            .AppendLine("- Refresh Model: write the graded result to a temp texture and push it to the 3D view (original untouched).")
            .AppendLine("- Save as New Texture: write xxx_new.png and point the material at it.")
            .AppendLine("- Revert / Reset Parameters / Undo / Redo.")
            .AppendLine()
            .AppendLine("[Non-destructive workflow]")
            .AppendLine("Sliders only change the in-memory preview; the original texture file is never touched.")
            .AppendLine("Use Refresh Model to preview in 3D, or Save as New Texture to write it to disk.")
            .AppendLine("Revert restores Material.Tex to its original value and cleans up temp files.")
            .AppendLine()
            .AppendLine("[Where the manual lives]")
            .AppendLine("- This file sits in the data folder next to the plug-in: data\\TextureGrade_Operation_EN.txt")
            .AppendLine("- One file per language: _EN / _SC (Simplified Chinese) / _TC (Traditional Chinese) / _JP (Japanese).")
            .AppendLine("- Missing files are generated automatically at start-up; existing ones are never overwritten.")
            .AppendLine("- Switching the UI language switches which file is read; edit the txt and click Reload to refresh.")
            .ToString();

        private static string Ja() => new StringBuilder()
            .AppendLine("Texture Grade — 操作説明")
            .AppendLine("（このファイルはプラグインが自動生成しました。自由に編集し、説明ウィンドウの「再読み込み」で反映できます）")
            .AppendLine()
            .AppendLine("【左パネル：テクスチャ + UV プレビュー】")
            .AppendLine("· ホイール：カーソル中心にズーム。右ドラッグ：どのモードでも平移。")
            .AppendLine("· クリック：UV 三角面を 1 枚選択（Shift で追加 / Ctrl で削除 / もう一度クリックで解除）")
            .AppendLine("· ダブルクリック：連結した UV アイランドをまとめて追加選択（Blender の L キー相当）。続けて別のアイランドをダブルクリックすれば複数同時選択、もう一度ダブルクリック（または Ctrl+ダブルクリック）で解除")
            .AppendLine("· 左ドラッグ：選択モードでは矩形選択、平移モードでは表示を移動")
            .AppendLine("· 「アイランド選択」ボタン：現在の選択を完全な連結アイランドに拡張（選択が触れているすべてのアイランドを補完し、既存の選択は消しません）")
            .AppendLine("· 「元画像比較」ボタン：元テクスチャと調整結果を切り替え（パラメータは保持）")
            .AppendLine("· ヒストグラム：RGB 重ね合わせ、リアルタイム更新（表示メニューで非表示可）")
            .AppendLine("· 選択範囲がある場合、調色は選択範囲のみに適用され、それ以外は元のまま")
            .AppendLine()
            .AppendLine("【右パネル：材質と調整】")
            .AppendLine("· 材質一覧：サムネイル + 番号·名称。「変更済み」は調整済みまたはモデルへ反映済み")
            .AppendLine("· プリセット / お気に入り：調整値を JSON で保存し、他材質へワンクリック適用（ダブルクリックで適用）")
            .AppendLine("· 調整：折りたたみグループ（基本 / カラー / Lab ホイール / HSL / カーブ·レベル·RGB·HSV / ディテール / エフェクト）")
            .AppendLine("· パラメータは材質ごとに記憶され、切り替えても失われません")
            .AppendLine()
            .AppendLine("【Lab カラーホイール（明度ロック）】")
            .AppendLine("· 外環 = 色相、内円 = 彩度。環上の色はすべて同じ明度 L*（等明度色相環）")
            .AppendLine("· 「明度 L* をロック」をオンにすると、色相/彩度のみ変化し各ピクセルの明度は不変")
            .AppendLine("· オフにすると明るさも目標色に近づきます")
            .AppendLine("· 「画像の明度を取得」は選択範囲（無ければ全体）の平均 L* にホイールを固定")
            .AppendLine("· 「画像の色相を取得」は画像の色を起点に微調整、「強度」で適用割合を指定")
            .AppendLine()
            .AppendLine("【ファイルメニュー】")
            .AppendLine("· UV レイアウトを書き出し…：透明背景 + ワイヤーフレームの PNG（テクスチャと同サイズで重ねられます）")
            .AppendLine("· 選択範囲マスクを書き出し…：選択した UV 面の白黒 PNG（白 = 選択）")
            .AppendLine("· 現在の材質マスクを書き出し…：現在の材質の全 UV 面の白黒 PNG（白 = その材質）")
            .AppendLine("· 全材質マスクを書き出し…：材質ごとに 1 枚（白 = その材質の UV 領域）")
            .AppendLine("· プリセットフォルダを開く：presets フォルダを開きます")
            .AppendLine()
            .AppendLine("【下部ボタン】")
            .AppendLine("· 再読み込み：PMX から材質とテクスチャを再取得")
            .AppendLine("· モデルを更新：調整結果を一時テクスチャに書き出し 3D ビューへ反映（元画像は不変）")
            .AppendLine("· 新規テクスチャに保存：xxx_new.png を書き出し、材質の参照先を変更")
            .AppendLine("· 元に戻す / パラメータリセット / 取り消し / やり直し")
            .AppendLine()
            .AppendLine("【非破壊ワークフロー】")
            .AppendLine("スライダーはメモリ上のプレビューを変更するだけで、元テクスチャは書き換えません。")
            .AppendLine("3D で確認するなら「モデルを更新」、保存するなら「新規テクスチャに保存」を使います。")
            .AppendLine("「元に戻す」で Material.Tex を元の値に復元し、一時ファイルを削除します。")
            .AppendLine()
            .AppendLine("【説明ファイルの場所】")
            .AppendLine("· このファイルはプラグイン配下の data フォルダにあります：data\\TextureGrade_Operation_JP.txt")
            .AppendLine("· 4 言語ぶん：_EN（English）/ _SC（简体中文）/ _TC（繁體中文）/ _JP（日本語）")
            .AppendLine("· 起動時に不足分は自動生成され、既存ファイルは上書きされません")
            .AppendLine("· 表示言語を切り替えると対応ファイルを読み直します。txt を編集したら「再読み込み」を押してください")
            .ToString();
    }
}
